import type { WatchObject } from "../types";

const TEAM_CN_NAMES: Record<string, string> = {
  ALG: "阿尔及利亚",
  ANG: "安哥拉",
  ARG: "阿根廷",
  ARG2: "阿根廷二队",
  AUS: "澳大利亚",
  AUT: "奥地利",
  BEL: "比利时",
  BIH: "波黑",
  BRA: "巴西",
  CAN: "加拿大",
  CHN: "中国",
  CIV: "科特迪瓦",
  CMR: "喀麦隆",
  COD: "刚果（金）",
  COL: "哥伦比亚",
  CPV: "佛得角",
  CRC: "哥斯达黎加",
  CRO: "克罗地亚",
  CUW: "库拉索",
  CZE: "捷克",
  DEN: "丹麦",
  ECU: "厄瓜多尔",
  EGY: "埃及",
  ENG: "英格兰",
  ESP: "西班牙",
  FRA: "法国",
  GER: "德国",
  GHA: "加纳",
  HAI: "海地",
  HON: "洪都拉斯",
  IRN: "伊朗",
  IRQ: "伊拉克",
  ISL: "冰岛",
  ITA: "意大利",
  JOR: "约旦",
  JPN: "日本",
  KOR: "韩国",
  KSA: "沙特阿拉伯",
  MAR: "摩洛哥",
  MEX: "墨西哥",
  NED: "荷兰",
  NGA: "尼日利亚",
  NGR: "尼日利亚",
  NOR: "挪威",
  NZL: "新西兰",
  PAN: "巴拿马",
  PAR: "巴拉圭",
  POR: "葡萄牙",
  QAT: "卡塔尔",
  RSA: "南非",
  SCO: "苏格兰",
  SEN: "塞内加尔",
  SLO: "斯洛文尼亚",
  SRB: "塞尔维亚",
  SUI: "瑞士",
  SWE: "瑞典",
  TGA: "汤加",
  TUN: "突尼斯",
  TUR: "土耳其",
  UKR: "乌克兰",
  URU: "乌拉圭",
  USA: "美国",
  UZB: "乌兹别克斯坦",
  WAL: "威尔士"
};

const EN_TO_CN: Record<string, string> = {
  "algeria": "阿尔及利亚",
  "angola": "安哥拉",
  "argentina": "阿根廷",
  "argentina ii": "阿根廷二队",
  "australia": "澳大利亚",
  "austria": "奥地利",
  "belgium": "比利时",
  "bosnia and herzegovina": "波黑",
  "brazil": "巴西",
  "cameroon": "喀麦隆",
  "canada": "加拿大",
  "cape verde": "佛得角",
  "china": "中国",
  "colombia": "哥伦比亚",
  "congo dr": "刚果（金）",
  "costa rica": "哥斯达黎加",
  "cote d'ivoire": "科特迪瓦",
  "croatia": "克罗地亚",
  "curaçao": "库拉索",
  "curacao": "库拉索",
  "czech republic": "捷克",
  "denmark": "丹麦",
  "ecuador": "厄瓜多尔",
  "egypt": "埃及",
  "england": "英格兰",
  "france": "法国",
  "germany": "德国",
  "ghana": "加纳",
  "haiti": "海地",
  "honduras": "洪都拉斯",
  "iceland": "冰岛",
  "iran": "伊朗",
  "iraq": "伊拉克",
  "italy": "意大利",
  "japan": "日本",
  "jordan": "约旦",
  "mexico": "墨西哥",
  "morocco": "摩洛哥",
  "netherlands": "荷兰",
  "new zealand": "新西兰",
  "nigeria": "尼日利亚",
  "norway": "挪威",
  "panama": "巴拿马",
  "paraguay": "巴拉圭",
  "portugal": "葡萄牙",
  "qatar": "卡塔尔",
  "saudi arabia": "沙特阿拉伯",
  "scotland": "苏格兰",
  "senegal": "塞内加尔",
  "serbia": "塞尔维亚",
  "slovenia": "斯洛文尼亚",
  "south africa": "南非",
  "south korea": "韩国",
  "spain": "西班牙",
  "sweden": "瑞典",
  "switzerland": "瑞士",
  "tonga": "汤加",
  "tunisia": "突尼斯",
  "turkey": "土耳其",
  "ukraine": "乌克兰",
  "united states": "美国",
  "uruguay": "乌拉圭",
  "usa": "美国",
  "uzbekistan": "乌兹别克斯坦",
  "wales": "威尔士"
};

export function teamDisplayName(team: WatchObject | undefined, fallback = "待定") {
  if (!team) return fallbackLabel(fallback);
  const symbol = team.symbol?.toUpperCase();
  if (symbol && TEAM_CN_NAMES[symbol]) return TEAM_CN_NAMES[symbol];
  const displayName = team.display_name?.trim();
  if (displayName) return EN_TO_CN[displayName.toLowerCase()] ?? displayName;
  return fallbackLabel(team.symbol || fallback);
}

export function teamShortName(team: WatchObject | undefined, fallback = "待定") {
  const name = teamDisplayName(team, fallback);
  return name.length > 5 ? name.slice(0, 5) : name;
}

export function fallbackLabel(value: string) {
  if (!value || value === "slot_tba") return "待定";
  return EN_TO_CN[value.toLowerCase()] ?? value;
}
